# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a3424e7429e81e98b759a0472274702621f53ad7b505fc59f23f00a94b1071b89f7e2c084a00a3d40fa3c10f7fda55d2e66e908b77bec0d031a54568ec2619c

test:
  secret_key_base: e02207138e5548313df9c84074109fe234fc1ef1f7e7da7c1b628dff23cff172896f5ee099981c2b2614364ff0ed58fe0f195ba7c8f39fac35e9fb67949177bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
